[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    ; Mantener en 0 cuando MATLAB usa el mismo puerto serial binario
    -DMASTER_SERIAL_LOG=0
    ; Desactivar martillo hasta tener acondicionamiento de señal
    -DHAMMER_BTN_ENABLED=0
    -DHAMMER_ACCEL_ENABLED=0
    ; Número de nodos esclavos esperados
    -DNUM_SLAVES=3
