[platformio]
default_envs = esp8266_nodemcuv2

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -DNODE_ID=1

[env:esp8266_nodemcuv2]
platform  = espressif8266
board     = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DNODE_ID=1

[env:esp8266_d1_mini]
platform  = espressif8266
board     = d1_mini
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DNODE_ID=1
