[platformio]
default_envs = slave1, slave2

[env:base_esp32]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -DSAMPLE_PULSE_PIN=14
    -DSAMPLE_PULSE_IDLE=0
    -DSAMPLE_PULSE_US=2

[env:slave1]
extends     = env:base_esp32
upload_port = COM9        ; <-- ajustar al COM real del esclavo 1
monitor_port= COM9
build_flags =
    ${env:base_esp32.build_flags}
    -DNODE_ID=1

[env:slave2]
extends     = env:base_esp32
upload_port = COM10       ; <-- ajustar al COM real del esclavo 2
monitor_port= COM10
build_flags =
    ${env:base_esp32.build_flags}
    -DNODE_ID=2
